name = "wendigo-pl-static"
compatibility_date = "2022-07-12"
account_id = "764f49066c0c120617aff1d59be3b9e2"
workers_dev = false
route = { pattern = "wendigo.pl/*", zone_name = "wendigo.pl" }

kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "6eed8e72bf444a18b486115b65c952ed" }
]

assets = { directory = "./public" }
